[2025-03-30T11:09:44.190+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:09:44.212+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:09:44.214+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:09:44.236+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:09:44.241+0000] {standard_task_runner.py:60} INFO - Started process 456 to run task
[2025-03-30T11:09:44.245+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpsb6tv2kn']
[2025-03-30T11:09:44.247+0000] {standard_task_runner.py:88} INFO - Job 201: Subtask ingest_dummy_data
[2025-03-30T11:09:44.260+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:09:44.317+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:09:44.466+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:09:44.476+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:09:44.480+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.481+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.482+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.484+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.485+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.486+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.488+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.488+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.489+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.491+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.492+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.494+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.495+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:09:44-2975' for key 'PRIMARY'")
[2025-03-30T11:09:44.496+0000] {inout_data.py:159} INFO - Ingested 14 rows of dummy data.
[2025-03-30T11:09:44.497+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:09:44.497+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:09:44.506+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T190000, start_date=20250330T110944, end_date=20250330T110944
[2025-03-30T11:09:44.550+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:09:44.568+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:16:21.246+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:16:21.261+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:16:21.262+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:16:21.301+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:16:21.314+0000] {standard_task_runner.py:60} INFO - Started process 2311 to run task
[2025-03-30T11:16:21.321+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '1129', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp15t1xmmj']
[2025-03-30T11:16:21.323+0000] {standard_task_runner.py:88} INFO - Job 1129: Subtask ingest_dummy_data
[2025-03-30T11:16:21.353+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:16:21.579+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:16:21.944+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:16:21.965+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:16:21.974+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:21.978+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:21.981+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:21.985+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:21.987+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:21.988+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:21.994+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:21.999+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:22.002+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:22.004+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:22.008+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:22.009+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:22.010+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:22.014+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:22.020+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:22.022+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:22.026+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:22.031+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:16:21-5589' for key 'PRIMARY'")
[2025-03-30T11:16:22.033+0000] {inout_data.py:152} INFO - Ingested 19 rows of dummy data.
[2025-03-30T11:16:22.037+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:16:22.039+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:16:22.094+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T190000, start_date=20250330T111621, end_date=20250330T111622
[2025-03-30T11:16:22.179+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:16:22.308+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:28:57.083+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:28:57.113+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:28:57.113+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:28:57.156+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:28:57.166+0000] {standard_task_runner.py:60} INFO - Started process 4232 to run task
[2025-03-30T11:28:57.172+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '2089', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpuh4dfhvr']
[2025-03-30T11:28:57.176+0000] {standard_task_runner.py:88} INFO - Job 2089: Subtask ingest_dummy_data
[2025-03-30T11:28:57.214+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:28:57.324+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:28:57.537+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:28:57.545+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:28:57.549+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.550+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.552+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.555+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.557+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.558+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.559+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.562+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.565+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.568+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.570+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.575+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.577+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.578+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.581+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.582+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:28:57.582+0000] {inout_data.py:87} INFO - Ingested 16 rows of dummy data for 2024-09-30 19:00:00+00:00.
[2025-03-30T11:28:57.583+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:28:57.584+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:28:57.600+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T190000, start_date=20250330T112857, end_date=20250330T112857
[2025-03-30T11:28:57.645+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:28:57.692+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:33:30.821+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:33:30.837+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:33:30.837+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:33:30.860+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:33:30.869+0000] {standard_task_runner.py:60} INFO - Started process 5686 to run task
[2025-03-30T11:33:30.878+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '2817', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmp2tc6cndk']
[2025-03-30T11:33:30.879+0000] {standard_task_runner.py:88} INFO - Job 2817: Subtask ingest_dummy_data
[2025-03-30T11:33:30.893+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:33:30.940+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:33:31.014+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:33:31.020+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:33:31.022+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 31, 22845), 'timestamp': datetime.datetime(2024, 9, 30, 19, 4, tzinfo=datetime.timezone.utc), 'emp_id': 6898, 'employee_name': 'Employee97', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:33:31.026+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:31.027+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 31, 27739), 'timestamp': datetime.datetime(2024, 9, 30, 19, 23, tzinfo=datetime.timezone.utc), 'emp_id': 4683, 'employee_name': 'Employee70', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '10', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:33:31.028+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:31.029+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 31, 29515), 'timestamp': datetime.datetime(2024, 9, 30, 19, 2, tzinfo=datetime.timezone.utc), 'emp_id': 5211, 'employee_name': 'Employee51', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '7', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:33:31.030+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:31.031+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 31, 31153), 'timestamp': datetime.datetime(2024, 9, 30, 19, 22, tzinfo=datetime.timezone.utc), 'emp_id': 8209, 'employee_name': 'Employee62', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '2', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:33:31.031+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:31.034+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 33, 31, 34206), 'timestamp': datetime.datetime(2024, 9, 30, 19, 29, tzinfo=datetime.timezone.utc), 'emp_id': 8233, 'employee_name': 'Employee15', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '7', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:33:31.037+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:33:31.040+0000] {inout_data.py:88} INFO - Ingested 5 rows of dummy data for 2024-09-30 19:00:00+00:00.
[2025-03-30T11:33:31.041+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:33:31.042+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:33:31.064+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T190000, start_date=20250330T113330, end_date=20250330T113331
[2025-03-30T11:33:31.143+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:33:31.170+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:39:09.151+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:39:09.166+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:39:09.167+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:39:09.218+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:39:09.224+0000] {standard_task_runner.py:60} INFO - Started process 6588 to run task
[2025-03-30T11:39:09.231+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '3268', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpjjiuhp1e']
[2025-03-30T11:39:09.232+0000] {standard_task_runner.py:88} INFO - Job 3268: Subtask ingest_dummy_data
[2025-03-30T11:39:09.247+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:39:09.284+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:39:09.374+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:39:09.382+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:39:09.385+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 385598), 'timestamp': datetime.datetime(2024, 9, 30, 19, 24, tzinfo=datetime.timezone.utc), 'emp_id': 5878, 'employee_name': 'Employee2', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '9', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:39:09.387+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.389+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 389890), 'timestamp': datetime.datetime(2024, 9, 30, 19, 19, tzinfo=datetime.timezone.utc), 'emp_id': 7973, 'employee_name': 'Employee12', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '4', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:39:09.390+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.392+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 392651), 'timestamp': datetime.datetime(2024, 9, 30, 19, 19, tzinfo=datetime.timezone.utc), 'emp_id': 2967, 'employee_name': 'Employee96', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:39:09.394+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.396+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 396097), 'timestamp': datetime.datetime(2024, 9, 30, 19, 0, tzinfo=datetime.timezone.utc), 'emp_id': 4690, 'employee_name': 'Employee31', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '7', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:39:09.397+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.399+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 398866), 'timestamp': datetime.datetime(2024, 9, 30, 19, 23, tzinfo=datetime.timezone.utc), 'emp_id': 8983, 'employee_name': 'Employee60', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '10', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:39:09.400+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.401+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 401130), 'timestamp': datetime.datetime(2024, 9, 30, 19, 4, tzinfo=datetime.timezone.utc), 'emp_id': 5886, 'employee_name': 'Employee24', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '10', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:39:09.402+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.404+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 404060), 'timestamp': datetime.datetime(2024, 9, 30, 19, 24, tzinfo=datetime.timezone.utc), 'emp_id': 7359, 'employee_name': 'Employee17', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '10', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:39:09.405+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.406+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 406005), 'timestamp': datetime.datetime(2024, 9, 30, 19, 11, tzinfo=datetime.timezone.utc), 'emp_id': 6504, 'employee_name': 'Employee12', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '4', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:39:09.407+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.408+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 407995), 'timestamp': datetime.datetime(2024, 9, 30, 19, 16, tzinfo=datetime.timezone.utc), 'emp_id': 3646, 'employee_name': 'Employee58', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '8', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:39:09.409+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.409+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 409603), 'timestamp': datetime.datetime(2024, 9, 30, 19, 22, tzinfo=datetime.timezone.utc), 'emp_id': 8217, 'employee_name': 'Employee58', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '2', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:39:09.414+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.415+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 415385), 'timestamp': datetime.datetime(2024, 9, 30, 19, 10, tzinfo=datetime.timezone.utc), 'emp_id': 9208, 'employee_name': 'Employee38', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:39:09.416+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.417+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 417527), 'timestamp': datetime.datetime(2024, 9, 30, 19, 5, tzinfo=datetime.timezone.utc), 'emp_id': 9881, 'employee_name': 'Employee73', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:39:09.419+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.423+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 422921), 'timestamp': datetime.datetime(2024, 9, 30, 19, 1, tzinfo=datetime.timezone.utc), 'emp_id': 7257, 'employee_name': 'Employee78', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '6', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:39:09.423+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.424+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 424823), 'timestamp': datetime.datetime(2024, 9, 30, 19, 12, tzinfo=datetime.timezone.utc), 'emp_id': 1019, 'employee_name': 'Employee64', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '8', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:39:09.426+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.427+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 427443), 'timestamp': datetime.datetime(2024, 9, 30, 19, 8, tzinfo=datetime.timezone.utc), 'emp_id': 5787, 'employee_name': 'Employee46', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '3', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:39:09.429+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.430+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 39, 9, 430556), 'timestamp': datetime.datetime(2024, 9, 30, 19, 28, tzinfo=datetime.timezone.utc), 'emp_id': 3669, 'employee_name': 'Employee33', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '4', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:39:09.431+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:39:09.432+0000] {inout_data.py:101} INFO - Ingested 16 rows of dummy data for 2024-09-30 19:00:00+00:00.
[2025-03-30T11:39:09.433+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:39:09.436+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:39:09.488+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T190000, start_date=20250330T113909, end_date=20250330T113909
[2025-03-30T11:39:09.542+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:39:09.567+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:41:15.494+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:41:15.556+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [queued]>
[2025-03-30T11:41:15.566+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:41:15.680+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-09-30 19:00:00+00:00
[2025-03-30T11:41:15.768+0000] {standard_task_runner.py:60} INFO - Started process 7027 to run task
[2025-03-30T11:41:15.796+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-09-30T19:00:00+00:00', '--job-id', '3487', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpmo0no7fn']
[2025-03-30T11:41:15.801+0000] {standard_task_runner.py:88} INFO - Job 3487: Subtask ingest_dummy_data
[2025-03-30T11:41:15.855+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:41:16.023+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-09-30T19:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:41:16.543+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-30T19:00:00+00:00'
[2025-03-30T11:41:16.576+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:41:16.583+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 581406), 'timestamp': datetime.datetime(2024, 9, 30, 19, 1, tzinfo=datetime.timezone.utc), 'emp_id': 5263, 'employee_name': 'Employee26', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '2', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:41:16.587+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.588+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:01:00', 5263, 'Employee26', 'FactoryA', 'IN', 'Main', '2', 'IT', 'BSID', 'ML', '1')
[2025-03-30T11:41:16.590+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.591+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 591443), 'timestamp': datetime.datetime(2024, 9, 30, 19, 11, tzinfo=datetime.timezone.utc), 'emp_id': 6189, 'employee_name': 'Employee31', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '3', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:41:16.593+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.594+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:11:00', 6189, 'Employee31', 'FactoryA', 'IN', 'Main', '3', 'IT', 'BSID', 'CAPD', '1')
[2025-03-30T11:41:16.597+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.599+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 599731), 'timestamp': datetime.datetime(2024, 9, 30, 19, 3, tzinfo=datetime.timezone.utc), 'emp_id': 8321, 'employee_name': 'Employee30', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '4', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:41:16.602+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.603+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:03:00', 8321, 'Employee30', 'FactoryB', 'IN', 'Side', '4', 'IT', 'BSID', 'CAPD', '1')
[2025-03-30T11:41:16.604+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.606+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 606399), 'timestamp': datetime.datetime(2024, 9, 30, 19, 4, tzinfo=datetime.timezone.utc), 'emp_id': 5859, 'employee_name': 'Employee4', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:41:16.608+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.608+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:04:00', 5859, 'Employee4', 'FactoryA', 'OUT', 'Main', '5', 'IT', 'BSID', 'ML', '2')
[2025-03-30T11:41:16.609+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.609+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 609358), 'timestamp': datetime.datetime(2024, 9, 30, 19, 12, tzinfo=datetime.timezone.utc), 'emp_id': 5122, 'employee_name': 'Employee47', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '5', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:41:16.609+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.610+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:12:00', 5122, 'Employee47', 'FactoryA', 'OUT', 'Side', '5', 'IT', 'AAPD', 'CAPD', '1')
[2025-03-30T11:41:16.610+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.612+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 612263), 'timestamp': datetime.datetime(2024, 9, 30, 19, 23, tzinfo=datetime.timezone.utc), 'emp_id': 6599, 'employee_name': 'Employee51', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '10', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:41:16.613+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.617+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:23:00', 6599, 'Employee51', 'FactoryB', 'OUT', 'Main', '10', 'IT', 'AAPD', 'CAPD', '1')
[2025-03-30T11:41:16.619+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.620+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 620015), 'timestamp': datetime.datetime(2024, 9, 30, 19, 16, tzinfo=datetime.timezone.utc), 'emp_id': 4688, 'employee_name': 'Employee7', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '7', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:41:16.624+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.626+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:16:00', 4688, 'Employee7', 'FactoryB', 'IN', 'Side', '7', 'IT', 'AAPD', 'ML', '2')
[2025-03-30T11:41:16.628+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.630+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 630507), 'timestamp': datetime.datetime(2024, 9, 30, 19, 29, tzinfo=datetime.timezone.utc), 'emp_id': 6667, 'employee_name': 'Employee8', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '4', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:41:16.632+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.633+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:29:00', 6667, 'Employee8', 'FactoryB', 'OUT', 'Side', '4', 'IT', 'BSID', 'ML', '1')
[2025-03-30T11:41:16.634+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.636+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 635946), 'timestamp': datetime.datetime(2024, 9, 30, 19, 4, tzinfo=datetime.timezone.utc), 'emp_id': 3050, 'employee_name': 'Employee95', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '9', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '2'}
[2025-03-30T11:41:16.637+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.638+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:04:00', 3050, 'Employee95', 'FactoryB', 'OUT', 'Main', '9', 'IT', 'AAPD', 'ML', '2')
[2025-03-30T11:41:16.640+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.641+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 641601), 'timestamp': datetime.datetime(2024, 9, 30, 19, 20, tzinfo=datetime.timezone.utc), 'emp_id': 6165, 'employee_name': 'Employee38', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:41:16.643+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.650+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:20:00', 6165, 'Employee38', 'FactoryB', 'IN', 'Main', '1', 'IT', 'AAPD', 'HRSD', '2')
[2025-03-30T11:41:16.656+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.660+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 660066), 'timestamp': datetime.datetime(2024, 9, 30, 19, 8, tzinfo=datetime.timezone.utc), 'emp_id': 1027, 'employee_name': 'Employee21', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '2', 'function': 'IT', 'division': 'AAPD', 'department': 'ML', 'section': '1'}
[2025-03-30T11:41:16.671+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.672+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:08:00', 1027, 'Employee21', 'FactoryB', 'IN', 'Side', '2', 'IT', 'AAPD', 'ML', '1')
[2025-03-30T11:41:16.673+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.675+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 675065), 'timestamp': datetime.datetime(2024, 9, 30, 19, 0, tzinfo=datetime.timezone.utc), 'emp_id': 2122, 'employee_name': 'Employee55', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '4', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:41:16.676+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.678+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:00:00', 2122, 'Employee55', 'FactoryA', 'IN', 'Main', '4', 'IT', 'BSID', 'CAPD', '2')
[2025-03-30T11:41:16.680+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.684+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 684429), 'timestamp': datetime.datetime(2024, 9, 30, 19, 8, tzinfo=datetime.timezone.utc), 'emp_id': 7802, 'employee_name': 'Employee94', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Side', 'door_number': '6', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '2'}
[2025-03-30T11:41:16.685+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.686+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:08:00', 7802, 'Employee94', 'FactoryB', 'IN', 'Side', '6', 'IT', 'BSID', 'ML', '2')
[2025-03-30T11:41:16.687+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.689+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 688989), 'timestamp': datetime.datetime(2024, 9, 30, 19, 23, tzinfo=datetime.timezone.utc), 'emp_id': 9001, 'employee_name': 'Employee94', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '8', 'function': 'IT', 'division': 'BSID', 'department': 'ML', 'section': '1'}
[2025-03-30T11:41:16.690+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.692+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:23:00', 9001, 'Employee94', 'FactoryA', 'IN', 'Main', '8', 'IT', 'BSID', 'ML', '1')
[2025-03-30T11:41:16.694+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.700+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 700510), 'timestamp': datetime.datetime(2024, 9, 30, 19, 9, tzinfo=datetime.timezone.utc), 'emp_id': 5923, 'employee_name': 'Employee15', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '5', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '2'}
[2025-03-30T11:41:16.702+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.704+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:09:00', 5923, 'Employee15', 'FactoryB', 'OUT', 'Main', '5', 'IT', 'BSID', 'CAPD', '2')
[2025-03-30T11:41:16.706+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.714+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 714027), 'timestamp': datetime.datetime(2024, 9, 30, 19, 2, tzinfo=datetime.timezone.utc), 'emp_id': 6415, 'employee_name': 'Employee30', 'factory': 'FactoryB', 'in_out': 'OUT', 'entrance': 'Side', 'door_number': '9', 'function': 'IT', 'division': 'BSID', 'department': 'HRSD', 'section': '2'}
[2025-03-30T11:41:16.714+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.715+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:02:00', 6415, 'Employee30', 'FactoryB', 'OUT', 'Side', '9', 'IT', 'BSID', 'HRSD', '2')
[2025-03-30T11:41:16.716+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.726+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 726302), 'timestamp': datetime.datetime(2024, 9, 30, 19, 11, tzinfo=datetime.timezone.utc), 'emp_id': 3879, 'employee_name': 'Employee72', 'factory': 'FactoryB', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '10', 'function': 'IT', 'division': 'AAPD', 'department': 'HRSD', 'section': '1'}
[2025-03-30T11:41:16.732+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.734+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:11:00', 3879, 'Employee72', 'FactoryB', 'IN', 'Main', '10', 'IT', 'AAPD', 'HRSD', '1')
[2025-03-30T11:41:16.735+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.736+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 736807), 'timestamp': datetime.datetime(2024, 9, 30, 19, 28, tzinfo=datetime.timezone.utc), 'emp_id': 4712, 'employee_name': 'Employee44', 'factory': 'FactoryA', 'in_out': 'OUT', 'entrance': 'Main', 'door_number': '9', 'function': 'IT', 'division': 'BSID', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:41:16.738+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.740+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:28:00', 4712, 'Employee44', 'FactoryA', 'OUT', 'Main', '9', 'IT', 'BSID', 'CAPD', '1')
[2025-03-30T11:41:16.742+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.745+0000] {inout_data.py:83} INFO - {'ingested_time': datetime.datetime(2025, 3, 30, 11, 41, 16, 744978), 'timestamp': datetime.datetime(2024, 9, 30, 19, 28, tzinfo=datetime.timezone.utc), 'emp_id': 5179, 'employee_name': 'Employee85', 'factory': 'FactoryA', 'in_out': 'IN', 'entrance': 'Main', 'door_number': '1', 'function': 'IT', 'division': 'AAPD', 'department': 'CAPD', 'section': '1'}
[2025-03-30T11:41:16.748+0000] {inout_data.py:99} INFO - Query: INSERT INTO emp_inout_rec (ingested_time, timestamp, employee_id, employee_name, factory, in_out, entrance, door_number, function, division, department, section) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
[2025-03-30T11:41:16.750+0000] {inout_data.py:100} INFO - Params: ('2025-03-30 11:41:16', '2024-09-30 19:28:00', 5179, 'Employee85', 'FactoryA', 'IN', 'Main', '1', 'IT', 'AAPD', 'CAPD', '1')
[2025-03-30T11:41:16.752+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:41:16.754+0000] {inout_data.py:102} INFO - Ingested 19 rows of dummy data for 2024-09-30 19:00:00+00:00.
[2025-03-30T11:41:16.756+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:41:16.757+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:41:16.802+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20240930T190000, start_date=20250330T114115, end_date=20250330T114116
[2025-03-30T11:41:16.935+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:41:17.061+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
