[2025-03-30T11:12:43.993+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-06T03:00:00+00:00 [queued]>
[2025-03-30T11:12:44.019+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-06T03:00:00+00:00 [queued]>
[2025-03-30T11:12:44.021+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:12:44.048+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-06 03:00:00+00:00
[2025-03-30T11:12:44.059+0000] {standard_task_runner.py:60} INFO - Started process 1485 to run task
[2025-03-30T11:12:44.068+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-06T03:00:00+00:00', '--job-id', '716', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpu4d5nxof']
[2025-03-30T11:12:44.073+0000] {standard_task_runner.py:88} INFO - Job 716: Subtask ingest_dummy_data
[2025-03-30T11:12:44.103+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:12:44.157+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-06T03:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:12:44.292+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-06T03:00:00+00:00'
[2025-03-30T11:12:44.300+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:12:44.304+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:44-7480' for key 'PRIMARY'")
[2025-03-30T11:12:44.306+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:44-7480' for key 'PRIMARY'")
[2025-03-30T11:12:44.307+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:44-7480' for key 'PRIMARY'")
[2025-03-30T11:12:44.309+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:44-7480' for key 'PRIMARY'")
[2025-03-30T11:12:44.311+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:44-7480' for key 'PRIMARY'")
[2025-03-30T11:12:44.312+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:44-7480' for key 'PRIMARY'")
[2025-03-30T11:12:44.313+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:44-7480' for key 'PRIMARY'")
[2025-03-30T11:12:44.316+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:44-7480' for key 'PRIMARY'")
[2025-03-30T11:12:44.317+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:44-7480' for key 'PRIMARY'")
[2025-03-30T11:12:44.318+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:44-7480' for key 'PRIMARY'")
[2025-03-30T11:12:44.319+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:12:44-7480' for key 'PRIMARY'")
[2025-03-30T11:12:44.319+0000] {inout_data.py:159} INFO - Ingested 12 rows of dummy data.
[2025-03-30T11:12:44.320+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:12:44.321+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:12:44.344+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241006T030000, start_date=20250330T111243, end_date=20250330T111244
[2025-03-30T11:12:44.415+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:12:44.506+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:19:21.113+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-06T03:00:00+00:00 [queued]>
[2025-03-30T11:19:21.124+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-06T03:00:00+00:00 [queued]>
[2025-03-30T11:19:21.125+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:19:21.138+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-06 03:00:00+00:00
[2025-03-30T11:19:21.145+0000] {standard_task_runner.py:60} INFO - Started process 3326 to run task
[2025-03-30T11:19:21.151+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-06T03:00:00+00:00', '--job-id', '1639', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpccebjpv8']
[2025-03-30T11:19:21.153+0000] {standard_task_runner.py:88} INFO - Job 1639: Subtask ingest_dummy_data
[2025-03-30T11:19:21.163+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:19:21.210+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-06T03:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:19:21.316+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-06T03:00:00+00:00'
[2025-03-30T11:19:21.319+0000] {inout_data.py:42} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:19:21.321+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.321+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.321+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.322+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.322+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.323+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.323+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.323+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.323+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.324+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.324+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.324+0000] {inout_data.py:63} ERROR - Error executing query: (1062, "Duplicate entry '2025-03-30 11:19:21-3078' for key 'PRIMARY'")
[2025-03-30T11:19:21.325+0000] {inout_data.py:152} INFO - Ingested 13 rows of dummy data.
[2025-03-30T11:19:21.325+0000] {inout_data.py:78} INFO - MariaDB connection closed.
[2025-03-30T11:19:21.325+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:19:21.333+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241006T030000, start_date=20250330T111921, end_date=20250330T111921
[2025-03-30T11:19:21.373+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:19:21.389+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T11:31:27.644+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-06T03:00:00+00:00 [queued]>
[2025-03-30T11:31:27.655+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-06T03:00:00+00:00 [queued]>
[2025-03-30T11:31:27.655+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-03-30T11:31:27.675+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): ingest_dummy_data> on 2024-10-06 03:00:00+00:00
[2025-03-30T11:31:27.681+0000] {standard_task_runner.py:60} INFO - Started process 5244 to run task
[2025-03-30T11:31:27.689+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inout_data_ingestion', 'ingest_dummy_data', 'scheduled__2024-10-06T03:00:00+00:00', '--job-id', '2597', '--raw', '--subdir', 'DAGS_FOLDER/inout_data.py', '--cfg-path', '/tmp/tmpffzidd1o']
[2025-03-30T11:31:27.692+0000] {standard_task_runner.py:88} INFO - Job 2597: Subtask ingest_dummy_data
[2025-03-30T11:31:27.717+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-30T11:31:27.769+0000] {task_command.py:423} INFO - Running <TaskInstance: inout_data_ingestion.ingest_dummy_data scheduled__2024-10-06T03:00:00+00:00 [running]> on host ff9d64b065e6
[2025-03-30T11:31:27.857+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inout_data_ingestion' AIRFLOW_CTX_TASK_ID='ingest_dummy_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-06T03:00:00+00:00'
[2025-03-30T11:31:27.861+0000] {logging_mixin.py:188} INFO - Successfully connected to MariaDB: INOUT on mariadb:3306
[2025-03-30T11:31:27.861+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.862+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.863+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.864+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.865+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.865+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.866+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.866+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.867+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.867+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.867+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.867+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.867+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.868+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.868+0000] {logging_mixin.py:188} INFO - General error executing query: not all arguments converted during string formatting
[2025-03-30T11:31:27.868+0000] {inout_data.py:88} INFO - Ingested 15 rows of dummy data for 2024-10-06 03:00:00+00:00.
[2025-03-30T11:31:27.868+0000] {logging_mixin.py:188} INFO - MariaDB connection closed.
[2025-03-30T11:31:27.869+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-03-30T11:31:27.877+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=inout_data_ingestion, task_id=ingest_dummy_data, execution_date=20241006T030000, start_date=20250330T113127, end_date=20250330T113127
[2025-03-30T11:31:27.914+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-30T11:31:27.932+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
